version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend/xmrt-dao-frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "DevGruGold"
    labels:
      - "dependencies"
      - "frontend"
    
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "DevGruGold"
    labels:
      - "dependencies"
      - "root"
    
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend/xmrt-dao-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "DevGruGold"
    labels:
      - "dependencies"
      - "backend"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    reviewers:
      - "DevGruGold"
    labels:
      - "dependencies"
      - "github-actions"
