services:
  - type: web
    name: xmrt-eliza
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python advanced_eliza_orchestrator.py
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
