services:
  - type: web
    name: xmrt-autonomous-eliza
    env: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.12.0
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main
    
databases:
  - name: xmrt-eliza-postgres
    plan: starter
