services:
  - type: web
    name: xmrt-ecosystem
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT main:app
    plan: free
    region: oregon
    branch: main
    rootDir: ./
    envVars:
      - key: PYTHON_VERSION
        value: 3.11