# render.yaml - The "No Doubt" Blueprint for Eliza

services:
  - type: web
    name: eliza-automation-service
    runtime: python
    plan: starter

    # This tells Render to work inside your service folder.
    rootDir: backend/ai-automation-service

    # These commands will now work perfectly.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn -w 4 -k uvicorn.workers.UvicornWorker launcher:app --bind 0.0.0.0:$PORT"

    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB3_RPC_URL
        sync: false
