# render.yaml - The Official Blueprint for Eliza's AI Automation Service

services:
  # The main Eliza AI Web Service from the ai-automation-service directory
  - type: web
    name: eliza-automation-service
    runtime: python
    plan: starter # You can upgrade this later to prevent spin-down

    # THE FIX: This is the magic line. It tells Render to work inside this folder.
    rootDir: backend/ai-automation-service

    # Build and Start Commands, run from the 'rootDir'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker autonomous_system_launcher:app --bind 0.0.0.0:$PORT"

    healthCheckPath: /health # We will add this endpoint to your code
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 10000
      - key: GITHUB_USERNAME
        value: DevGruGold
      - key: ELIZA_ENV
        value: production
      # Secrets (you will set these in the Render Dashboard)
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB3_RPC_URL
        sync: false
      # Service Connections (Render handles these automatically)
      - key: REDIS_URL
        fromService:
          type: redis
          name: eliza-memory-cache
          property: connectionString

  # The Redis Cache for Eliza's Memory
  - type: redis
    name: eliza-memory-cache
    plan: free
