# render.yaml - The "No Doubt" Blueprint for Eliza v3.5

services:
  - type: web
    name: eliza-automation-service
    runtime: python
    plan: starter # You can upgrade this later to prevent spin-down

    # THE DEFINITIVE FIX: Pin a stable Python version with pre-compiled packages.
    # This avoids the need for the Rust compiler to run at all.
    pythonVersion: "3.11"

    # This tells Render to work inside your service folder.
    rootDir: .

    # These commands will now work perfectly in the new environment.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m uvicorn unified_eliza_agent:app --host 0.0.0.0 --port $PORT"

    healthCheckPath: /health # The endpoint in your launcher.py
    
    envVars:
      # Secrets must be set in the Render Dashboard Environment tab.
      - key: GITHUB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEB3_RPC_URL
        sync: false


