import json
from typing import Dict, Any

class EdgeFunctionArchitect:
    """
    Autonomous Supabase Edge Function Generator (Edge Architect).
    Enables Eliza to analyze tasks and generate Supabase Edge Functions.
    """

    def __init__(self):
        pass

    def analyze_task(self, task_description: str) -> bool:
        """
        Analyzes a task description to determine if a serverless Edge Function is suitable.
        Simple heuristic: looks for keywords related to high-compute, external API integration, or event-driven tasks.
        """
        keywords = ["api", "webhook", "process", "compute", "scaling", "latency", "serverless", "function"]
        task_lower = task_description.lower()
        return any(keyword in task_lower for keyword in keywords)

    def generate_function(self, name: str, capability: str) -> Dict[str, Any]:
        """
        Generates a Supabase Edge Function template (TypeScript/Deno).
        
        Args:
            name: The name of the function (e.g., 'process-image').
            capability: A brief description of what the function should do.
            
        Returns:
            A dictionary containing the function code and deployment instructions.
        """
        
        # Basic TypeScript template for Deno/Supabase Edge Functions
        ts_code = f"""
// Supabase Edge Function: {name}
// Capability: {capability}
// Generated by EdgeFunctionArchitect

import {{ serve }} from "https://deno.land/std@0.168.0/http/server.ts";

console.log("Function '{name}' up and running!");

serve(async (req) => {{
  try {{
    const {{ name }} = await req.json();
    const data = {{
      message: `Hello ${{name}}! This function handles: {capability}`,
      timestamp: new Date().toISOString(),
    }};

    return new Response(
      JSON.stringify(data),
      {{ headers: {{ "Content-Type": "application/json" }} }},
    );
  }} catch (error) {{
    return new Response(
      JSON.stringify({{ error: error.message }}),
      {{ status: 400, headers: {{ "Content-Type": "application/json" }} }},
    );
  }}
}});
"""

        deploy_instructions = f"""
# Deployment Instructions for '{name}'

1. Ensure you have the Supabase CLI installed.
2. Login: `supabase login`
3. Initialize project if needed: `supabase init`
4. Create the function: `supabase functions new {name}`
5. Replace the content of `supabase/functions/{name}/index.ts` with the generated code.
6. Deploy: `supabase functions deploy {name}`
"""

        return {
            "function_name": name,
            "code": ts_code.strip(),
            "instructions": deploy_instructions.strip()
        }

if __name__ == "__main__":
    # Simple test
    architect = EdgeFunctionArchitect()
    task = "Create an API to process user images"
    if architect.analyze_task(task):
        print(f"Task '{task}' requires an Edge Function.")
        result = architect.generate_function("process-images", "Image processing via external API")
        print(json.dumps(result, indent=2))
    else:
        print(f"Task '{task}' does not require an Edge Function.")
