[package]
name = "xmrt_ecosystem"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.3.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0" }

[dev-dependencies]
cairo_test = ">=2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.cairo]
enable-gas-profiler = true

[tool.snforge]
# Add any snforge-specific configuration here

[scripts]
build = "scarb build"
test = "scarb test"
format = "scarb fmt"

[profile.dev]
sierra-replace-ids = true

[profile.release]
sierra-replace-ids = false

